/**
 * This is an automatically generated class. It was generated by the
 * ECNO framework. This class defines an ECNO Instance which can
 * be started via the main method (Run As -> Java Application).
 */
package dk.dtu.compute.se.richard.planes.instances;

import dk.dtu.imm.se.ecno.engine.ExecutionEngine;
import dk.dtu.imm.se.ecno.gui.ECNOGUI;

public class Grid {

    final private planes.PlanesFactory factory1;

	public Grid() {
		factory1 = planes.PlanesFactory.eINSTANCE;
	}

	private void createInstance(ExecutionEngine engine) {
		// Create the objects
        planes.Field o1 = factory1.createField();
        planes.Field o2 = factory1.createField();
        planes.Field o3 = factory1.createField();
        planes.Field o4 = factory1.createField();
        planes.Plane o5 = factory1.createPlane();
        planes.Plane o6 = factory1.createPlane();
        planes.Plane o7 = factory1.createPlane();
        planes.Bird o8 = factory1.createBird();
        planes.Bird o9 = factory1.createBird();
        planes.Bird o10 = factory1.createBird();	

		// Set the (simple) attributes
        o1.setName("1");
        o2.setName("2");
        o3.setName("3");
        o4.setName("4");
        o5.setId(1);
        o6.setId(2);
        o7.setId(3);
        o8.setId(4);
        o9.setId(6);
        o10.setId(5);	
   
		// Create the single references
        o5.setField(o1);
        o6.setField(o2);
        o8.setField(o2);
        o9.setField(o2);
        o10.setField(o3);	

		// Create the multi references
        o1.getNeighbour().add(o4);
        o1.getNeighbour().add(o2);
        o2.getNeighbour().add(o1);
        o2.getNeighbour().add(o3);
        o3.getNeighbour().add(o2);
        o3.getNeighbour().add(o4);
        o4.getNeighbour().add(o3);
        o4.getNeighbour().add(o1);
        o6.getProximity().add(o8);
        o6.getProximity().add(o9);
        o8.getProximity().add(o6);
        o8.getProximity().add(o9);
        o9.getProximity().add(o6);
        o9.getProximity().add(o8);	
   		
		// Register the GUI objects with the controllers (objects 
		// not visible at a GUI will be added to the engine on the fly)
        engine.addElement(o5);
        engine.addElement(o6);
        engine.addElement(o7);
        engine.addElement(o8);
        engine.addElement(o9);
        engine.addElement(o10);
	}

    public static void main(String[] args) {
    	ExecutionEngine engine = ExecutionEngine.createNewInstance();
    	engine.addPackageAdapter(dk.dtu.compute.se.richard.planes.coordination.PlanesModel.getModel(engine));
    	if (!engine.resolveNamespaceImports()) {
    		System.err.println("Package imports could not be resolved");
    	}
    	new ECNOGUI(engine);
    	Grid instance = new Grid();
    	instance.createInstance(engine);
    }

}
