/**
 * This is an automatically generated class. It was generated by the
 * ECNO framework. This class defines an ECNO Instance which can
 * be started via the main method (Run As -> Java Application).
 */
package dk.dtu.compute.se.richard.planes.instances;

import dk.dtu.imm.se.ecno.engine.ExecutionEngine;
import dk.dtu.imm.se.ecno.gui.ECNOGUI;

public class Grid {

    final private planes.PlanesFactory factory1;

	public Grid() {
		factory1 = planes.PlanesFactory.eINSTANCE;
	}

	private void createInstance(ExecutionEngine engine) {
		// Create the objects
        planes.Plane o1 = factory1.createPlane();
        planes.Plane o2 = factory1.createPlane();
        planes.Bird o3 = factory1.createBird();
        planes.Bird o4 = factory1.createBird();
        planes.Field o5 = factory1.createField();
        planes.Field o6 = factory1.createField();
        planes.Field o7 = factory1.createField();
        planes.Field o8 = factory1.createField();	

		// Set the (simple) attributes
        o1.setId(1);
        o2.setId(2);
        o3.setId(0);
        o4.setId(2);
        o5.setName("0");
        o6.setName("1");
        o7.setName("2");
        o8.setName("3");	
   
		// Create the single references
        o1.setField(o6);
        o2.setField(o7);
        o5.setBird(o3);
        o7.setBird(o4);	

		// Create the multi references	
   		
		// Register the GUI objects with the controllers (objects 
		// not visible at a GUI will be added to the engine on the fly)
        engine.addElement(o1);
        engine.addElement(o2);
        engine.addElement(o3);
        engine.addElement(o4);
        engine.addElement(o5);
        engine.addElement(o6);
        engine.addElement(o7);
        engine.addElement(o8);
	}

    public static void main(String[] args) {
    	ExecutionEngine engine = ExecutionEngine.createNewInstance();
    	engine.addPackageAdapter(dk.dtu.compute.se.richard.planes.coordination.PlanesModel.getModel(engine));
    	if (!engine.resolveNamespaceImports()) {
    		System.err.println("Package imports could not be resolved");
    	}
    	new ECNOGUI(engine);
    	Grid instance = new Grid();
    	instance.createInstance(engine);
    }

}
