/**
 * This is an automatically generated class. It was generated by the
 * ECNO framework. This class defines ECNOPackageAdapterFactory and which 
 * provides access to the package adapter of the model for the ECNO EMF engine.
 */
package dk.dtu.compute.se.richard.planes.coordination;

import dk.dtu.imm.se.ecno.eclipse.adapterfactory.IPackageAdapterFactory;
import dk.dtu.imm.se.ecno.engine.ExecutionEngine;

public class PlanesFactory implements IPackageAdapterFactory {

	public PlanesModel getModel(ExecutionEngine engine) {
		return PlanesModel.getModel(engine);
	}

	public String getECNOPackageURI() {
		return "planes.ECNO";
	}

}
